-- Generated by Oracle SQL Developer Data Modeler 21.4.1.349.1605
--   at:        2022-03-16 09:25:52 BRT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g





DROP TABLE t_iud_cadastro CASCADE CONSTRAINTS;

DROP TABLE t_iud_cargos CASCADE CONSTRAINTS;

DROP TABLE t_iud_categoria_prod CASCADE CONSTRAINTS;

DROP TABLE t_iud_categoria_video CASCADE CONSTRAINTS;

DROP TABLE t_iud_chamado CASCADE CONSTRAINTS;

DROP TABLE t_iud_cliente CASCADE CONSTRAINTS;

DROP TABLE t_iud_departamento CASCADE CONSTRAINTS;

DROP TABLE t_iud_funcionario CASCADE CONSTRAINTS;

DROP TABLE t_iud_genero_cli CASCADE CONSTRAINTS;

DROP TABLE t_iud_produto CASCADE CONSTRAINTS;

DROP TABLE t_iud_res_chamado CASCADE CONSTRAINTS;

DROP TABLE t_iud_status_cat CASCADE CONSTRAINTS;

DROP TABLE t_iud_status_cham CASCADE CONSTRAINTS;

DROP TABLE t_iud_status_prod CASCADE CONSTRAINTS;

DROP TABLE t_iud_status_video CASCADE CONSTRAINTS;

DROP TABLE t_iud_tipo_chamado CASCADE CONSTRAINTS;

DROP TABLE t_iud_tipo_cliente CASCADE CONSTRAINTS;

DROP TABLE t_iud_video_prod CASCADE CONSTRAINTS;

DROP TABLE t_iud_views_video CASCADE CONSTRAINTS;




DROP SEQUENCE  T_IUD_CARGOS_COD_CARGO_SEQ;

DROP SEQUENCE T_IUD_CATEGORIA_PROD_COD_CATEG;

DROP SEQUENCE T_IUD_CATEGORIA_VIDEO_COD_CAT_;

DROP SEQUENCE T_IUD_DEPARTAMENTO_COD_DP_SEQ;

DROP SEQUENCE T_IUD_TIPO_CHAMADO_COD_TIPO_CH ;

DROP SEQUENCE T_IUD_TIPO_CLIENTE_COD_TIPO;

DROP SEQUENCE T_IUD_CADASTRO_COD_CAD;

DROP SEQUENCE T_IUD_VIEWS_VIDEO_COD_VIEW;

DROP SEQUENCE T_IUD_PRODUTO_COD_PRODUTO;

DROP SEQUENCE T_IUD_VIDEO_PROD_COD_VIDEO;






-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE t_iud_cadastro (
    cod_cadastro NUMBER(5) NOT NULL,
    nm_nome      VARCHAR2(150) NOT NULL,
    ddd_tel      VARCHAR2(15) NOT NULL,
    dt_nasc      DATE NOT NULL,
    email        VARCHAR2(100) NOT NULL
    
);


ALTER TABLE t_iud_cadastro ADD CONSTRAINT t_iud_cadastro_pk PRIMARY KEY ( cod_cadastro );

CREATE TABLE t_iud_cargos (
    cod_cargo NUMBER(5) NOT NULL,
    ds_cargo  VARCHAR2(50) NOT NULL
);

ALTER TABLE t_iud_cargos ADD CONSTRAINT t_iud_cargos_pk PRIMARY KEY ( cod_cargo );

CREATE TABLE t_iud_categoria_prod (
    cod_categoria  NUMBER(2) NOT NULL,
    ds_categoria   VARCHAR2(255) NOT NULL,
    dt_inicio      DATE NOT NULL,
    dt_termino     DATE,
    cod_status_cat CHAR(1) NOT NULL
);

ALTER TABLE t_iud_categoria_prod ADD CONSTRAINT t_iud_categoria_prod_pk PRIMARY KEY ( cod_categoria );

CREATE TABLE t_iud_categoria_video (
    cod_cat_video NUMBER(2) NOT NULL,
    nm_cat_video  VARCHAR2(100)
);

ALTER TABLE t_iud_categoria_video ADD CONSTRAINT t_iud_categoria_video_pk PRIMARY KEY ( cod_cat_video );

CREATE TABLE t_iud_chamado (
    cod_chamado         NUMBER(10) NOT NULL,
    cod_cad_funcionario NUMBER(5) NOT NULL,
    cod_cad_cliente     NUMBER(5) NOT NULL,
    txt_chamado         LONG,
    dt_abertura         DATE NOT NULL,
    dt_fechamento       DATE,
    qt_horas            INTEGER,
    cod_tipo_cham       NUMBER(2) NOT NULL,
    cod_st_chamado      CHAR(1) NOT NULL,
    cod_produto         NUMBER(5) NOT NULL
);

ALTER TABLE t_iud_chamado
    ADD CONSTRAINT t_iud_chamado_pk PRIMARY KEY ( cod_chamado,
                                                  cod_cad_funcionario,
                                                  cod_cad_cliente );

CREATE TABLE t_iud_cliente (
    cod_cadastro  NUMBER(5) NOT NULL,
    dt_ult_acesso DATE,
    cod_tipo      NUMBER(2) NOT NULL,
    cod_genero    CHAR(1) NOT NULL
);

CREATE UNIQUE INDEX t_iud_cliente__idx ON
    t_iud_cliente (
        cod_genero
    ASC );

ALTER TABLE t_iud_cliente ADD CONSTRAINT t_iud_cliente_pk PRIMARY KEY ( cod_cadastro );

CREATE TABLE t_iud_departamento (
    cod_dp NUMBER(2) NOT NULL,
    ds_dp  VARCHAR2(50) NOT NULL
);

ALTER TABLE t_iud_departamento ADD CONSTRAINT t_iud_departamento_pk PRIMARY KEY ( cod_dp );

CREATE TABLE t_iud_funcionario (
    cod_cadastro NUMBER(5) NOT NULL,
    cod_cargo    NUMBER(5) NOT NULL,
    cod_dp       NUMBER(2) NOT NULL
);

ALTER TABLE t_iud_funcionario ADD CONSTRAINT t_iud_funcionario_pk PRIMARY KEY ( cod_cadastro );

CREATE TABLE t_iud_genero_cli (
    cod_genero CHAR(1) NOT NULL,
    ds_genero  CHAR(1)
);

ALTER TABLE t_iud_genero_cli ADD CONSTRAINT t_iud_genero_cli_pk PRIMARY KEY ( cod_genero );

CREATE TABLE t_iud_produto (
    cod_produto     NUMBER(5) NOT NULL,
    nm_produto      VARCHAR2(255),
    desc_produto    CLOB,
    cod_barras      VARCHAR2(255),
    vl_un           NUMBER(10, 2),
    cod_categoria   NUMBER(2) NOT NULL,
    cod_status_prod CHAR(1) NOT NULL
);

ALTER TABLE t_iud_produto ADD CONSTRAINT t_iud_produto_pk PRIMARY KEY ( cod_produto );

CREATE TABLE t_iud_res_chamado (
    cod_resolucao       NUMBER(10) NOT NULL,
    txt_retorno         LONG,
    dt_atendimento      DATE,
    ind_satisfacao      NUMBER(2),
    cod_chamado         NUMBER(10) NOT NULL,
    cod_cad_funcionario NUMBER(5) NOT NULL,
    cod_cad_cliente     NUMBER(5) NOT NULL
);

CREATE UNIQUE INDEX t_iud_res_chamado__idx ON
    t_iud_res_chamado (
        cod_chamado
    ASC );

ALTER TABLE t_iud_res_chamado ADD CONSTRAINT t_iud_res_chamado_pk PRIMARY KEY ( cod_resolucao );

CREATE TABLE t_iud_status_cat (
    cod_status_cat CHAR(1) NOT NULL,
    ds_status      VARCHAR2(25) NOT NULL
);

COMMENT ON COLUMN t_iud_status_cat.ds_status IS
    'I: inativo, A: Ativo';

ALTER TABLE t_iud_status_cat ADD CONSTRAINT t_iud_status_cat_pk PRIMARY KEY ( cod_status_cat );

CREATE TABLE t_iud_status_cham (
    cod_st_chamado CHAR(1) NOT NULL,
    ds_st_chamado  VARCHAR2(100)
);

COMMENT ON COLUMN t_iud_status_cham.cod_st_chamado IS
    'Os principais status são: “A” (aberto) e o primeiro status criado no início, “E” (em atendimento), “C” (cancelado)”, “F” (fechado com sucesso), “X” (fechado com insatisfação do cliente),';

ALTER TABLE t_iud_status_cham ADD CONSTRAINT t_iud_status_cham_pk PRIMARY KEY ( cod_st_chamado );

CREATE TABLE t_iud_status_prod (
    cod_status_prod CHAR(1) NOT NULL,
    ds_status       VARCHAR2(25) NOT NULL
);

COMMENT ON COLUMN t_iud_status_prod.cod_status_prod IS
    'I: inativo, P: prospeccao, A: Ativo';

COMMENT ON COLUMN t_iud_status_prod.ds_status IS
    'I: inativo, P: prospeccao, A: Ativo';

ALTER TABLE t_iud_status_prod ADD CONSTRAINT t_iud_status_prod_pk PRIMARY KEY ( cod_status_prod );

CREATE TABLE t_iud_status_video (
    cod_status_video CHAR(1) NOT NULL,
    ds_status        VARCHAR2(25) NOT NULL
);

ALTER TABLE t_iud_status_video ADD CONSTRAINT t_iud_status_video_pk PRIMARY KEY ( cod_status_video );

CREATE TABLE t_iud_tipo_chamado (
    cod_tipo_cham NUMBER(2) NOT NULL,
    ds_chamado    VARCHAR2(45)
);

ALTER TABLE t_iud_tipo_chamado ADD CONSTRAINT t_iud_tipo_chamado_pk PRIMARY KEY ( cod_tipo_cham );

CREATE TABLE t_iud_tipo_cliente (
    cod_tipo NUMBER(2) NOT NULL,
    ds_tipo  VARCHAR2(100) NOT NULL
);

ALTER TABLE t_iud_tipo_cliente ADD CONSTRAINT t_iud_tipo_cliente_pk PRIMARY KEY ( cod_tipo );

CREATE TABLE t_iud_video_prod (
    cod_video        NUMBER(5) NOT NULL,
    link_video       VARCHAR2(500),
    cod_produto      NUMBER(5) NOT NULL,
    cod_status_video CHAR(1) NOT NULL,
    cod_cat_video    NUMBER(2) NOT NULL
);

ALTER TABLE t_iud_video_prod ADD CONSTRAINT t_iud_video_prod_pk PRIMARY KEY ( cod_video );

CREATE TABLE t_iud_views_video (
    cod_view     NUMBER(10) NOT NULL,
    cod_video    NUMBER(5) NOT NULL,
    dt_visita    DATE,
    cod_cadastro NUMBER(5)
);

ALTER TABLE t_iud_views_video ADD CONSTRAINT t_iud_views_video_pk PRIMARY KEY ( cod_view );

ALTER TABLE t_iud_cliente
    ADD CONSTRAINT t_iud_cadastro_fk FOREIGN KEY ( cod_cadastro )
        REFERENCES t_iud_cadastro ( cod_cadastro );

ALTER TABLE t_iud_funcionario
    ADD CONSTRAINT t_iud_cadastro_fkv2 FOREIGN KEY ( cod_cadastro )
        REFERENCES t_iud_cadastro ( cod_cadastro );

ALTER TABLE t_iud_funcionario
    ADD CONSTRAINT t_iud_cargos_fk FOREIGN KEY ( cod_cargo )
        REFERENCES t_iud_cargos ( cod_cargo );

ALTER TABLE t_iud_produto
    ADD CONSTRAINT t_iud_categoria_prod_fk FOREIGN KEY ( cod_categoria )
        REFERENCES t_iud_categoria_prod ( cod_categoria );

ALTER TABLE t_iud_video_prod
    ADD CONSTRAINT t_iud_categoria_video_fk FOREIGN KEY ( cod_cat_video )
        REFERENCES t_iud_categoria_video ( cod_cat_video );

ALTER TABLE t_iud_res_chamado
    ADD CONSTRAINT t_iud_chamado_fk FOREIGN KEY ( cod_chamado,
                                                  cod_cad_funcionario,
                                                  cod_cad_cliente )
        REFERENCES t_iud_chamado ( cod_chamado,
                                   cod_cad_funcionario,
                                   cod_cad_cliente );

ALTER TABLE t_iud_chamado
    ADD CONSTRAINT t_iud_cliente_fk FOREIGN KEY ( cod_cad_cliente )
        REFERENCES t_iud_cliente ( cod_cadastro );

ALTER TABLE t_iud_views_video
    ADD CONSTRAINT t_iud_cliente_fkv2 FOREIGN KEY ( cod_cadastro )
        REFERENCES t_iud_cliente ( cod_cadastro );

ALTER TABLE t_iud_funcionario
    ADD CONSTRAINT t_iud_departamento_fk FOREIGN KEY ( cod_dp )
        REFERENCES t_iud_departamento ( cod_dp );

ALTER TABLE t_iud_chamado
    ADD CONSTRAINT t_iud_funcionario_fk FOREIGN KEY ( cod_cad_funcionario )
        REFERENCES t_iud_funcionario ( cod_cadastro );

ALTER TABLE t_iud_cliente
    ADD CONSTRAINT t_iud_genero_cli_fk FOREIGN KEY ( cod_genero )
        REFERENCES t_iud_genero_cli ( cod_genero );

ALTER TABLE t_iud_video_prod
    ADD CONSTRAINT t_iud_produto_fk FOREIGN KEY ( cod_produto )
        REFERENCES t_iud_produto ( cod_produto );

ALTER TABLE t_iud_chamado
    ADD CONSTRAINT t_iud_produto_fkv2 FOREIGN KEY ( cod_produto )
        REFERENCES t_iud_produto ( cod_produto );

ALTER TABLE t_iud_categoria_prod
    ADD CONSTRAINT t_iud_status_cat_fk FOREIGN KEY ( cod_status_cat )
        REFERENCES t_iud_status_cat ( cod_status_cat );

ALTER TABLE t_iud_chamado
    ADD CONSTRAINT t_iud_status_cham_fk FOREIGN KEY ( cod_st_chamado )
        REFERENCES t_iud_status_cham ( cod_st_chamado );

ALTER TABLE t_iud_produto
    ADD CONSTRAINT t_iud_status_prod_fk FOREIGN KEY ( cod_status_prod )
        REFERENCES t_iud_status_prod ( cod_status_prod );

ALTER TABLE t_iud_video_prod
    ADD CONSTRAINT t_iud_status_video_fk FOREIGN KEY ( cod_status_video )
        REFERENCES t_iud_status_video ( cod_status_video );

ALTER TABLE t_iud_chamado
    ADD CONSTRAINT t_iud_tipo_chamado_fk FOREIGN KEY ( cod_tipo_cham )
        REFERENCES t_iud_tipo_chamado ( cod_tipo_cham );

ALTER TABLE t_iud_cliente
    ADD CONSTRAINT t_iud_tipo_cliente_fk FOREIGN KEY ( cod_tipo )
        REFERENCES t_iud_tipo_cliente ( cod_tipo );

ALTER TABLE t_iud_views_video
    ADD CONSTRAINT t_iud_video_prod_fk FOREIGN KEY ( cod_video )
        REFERENCES t_iud_video_prod ( cod_video );



CREATE SEQUENCE T_IUD_CARGOS_COD_CARGO_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER T_IUD_CARGOS_COD_CARGO_TRG 
BEFORE INSERT ON T_IUD_CARGOS 
FOR EACH ROW 
WHEN (NEW.COD_CARGO IS NULL) 
BEGIN
:new.cod_cargo := t_iud_cargos_cod_cargo_seq.nextval;

end;
/

CREATE SEQUENCE T_IUD_CATEGORIA_PROD_COD_CATEG 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER T_IUD_CATEGORIA_PROD_COD_CATEG 
BEFORE INSERT ON T_IUD_CATEGORIA_PROD 
FOR EACH ROW 
WHEN (NEW.COD_CATEGORIA IS NULL) 
BEGIN
:new.cod_categoria := t_iud_categoria_prod_cod_categ.nextval;

end;
/

CREATE SEQUENCE T_IUD_CATEGORIA_VIDEO_COD_CAT_ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER T_IUD_CATEGORIA_VIDEO_COD_CAT_ 
BEFORE INSERT ON T_IUD_CATEGORIA_VIDEO 
FOR EACH ROW 
WHEN (NEW.COD_CAT_VIDEO IS NULL) 
BEGIN
:new.cod_cat_video := t_iud_categoria_video_cod_cat_.nextval;

end;
/

CREATE SEQUENCE T_IUD_DEPARTAMENTO_COD_DP_SEQ 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER T_IUD_DEPARTAMENTO_COD_DP_TRG 
BEFORE INSERT ON T_IUD_DEPARTAMENTO 
FOR EACH ROW 
WHEN (NEW.COD_DP IS NULL) 
BEGIN
:new.cod_dp := t_iud_departamento_cod_dp_seq.nextval;

end;
/

CREATE SEQUENCE T_IUD_TIPO_CHAMADO_COD_TIPO_CH 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER T_IUD_TIPO_CHAMADO_COD_TIPO_CH 
BEFORE INSERT ON T_IUD_TIPO_CHAMADO 
FOR EACH ROW 
WHEN (NEW.COD_TIPO_CHAM IS NULL) 
BEGIN
:new.cod_tipo_cham := t_iud_tipo_chamado_cod_tipo_ch.nextval;

end;
/

CREATE SEQUENCE T_IUD_TIPO_CLIENTE_COD_TIPO 
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER T_IUD_TIPO_CLIENTE_COD_TIPO 
BEFORE INSERT ON T_IUD_TIPO_CLIENTE 
FOR EACH ROW 
WHEN (NEW.COD_TIPO IS NULL) 
BEGIN
:new.cod_tipo := t_iud_tipo_cliente_cod_tipo.nextval;

end;
/



CREATE SEQUENCE T_IUD_CADASTRO_COD_CAD
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER T_IUD_CADASTRO_COD_CAD
BEFORE INSERT ON T_IUD_CADASTRO 
FOR EACH ROW 
WHEN (NEW.COD_CADASTRO IS NULL) 
BEGIN
:new.cod_cadastro := t_iud_cadastro_cod_cad.nextval;

end;
/


CREATE SEQUENCE T_IUD_VIEWS_VIDEO_COD_VIEW
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER  T_IUD_VIEWS_VIDEO_COD_VIEW
BEFORE INSERT ON T_IUD_VIEWS_VIDEO
FOR EACH ROW 
WHEN (NEW.COD_VIEW IS NULL) 
BEGIN
:new.cod_view := T_IUD_VIEWS_VIDEO_COD_VIEW.nextval;

end;
/

CREATE SEQUENCE  T_IUD_PRODUTO_COD_PRODUTO
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER  T_IUD_PRODUTO_COD_PRODUTO
BEFORE INSERT ON T_IUD_PRODUTO
FOR EACH ROW 
WHEN (NEW.COD_PRODUTO IS NULL) 
BEGIN
:new.COD_PRODUTO := T_IUD_PRODUTO_COD_PRODUTO.nextval;

end;
/


CREATE SEQUENCE T_IUD_VIDEO_PROD_COD_VIDEO
START WITH 1 
    NOCACHE 
    ORDER ;

CREATE OR REPLACE TRIGGER  T_IUD_VIDEO_PROD_COD_VIDEO
BEFORE INSERT ON T_IUD_VIDEO_PROD
FOR EACH ROW 
WHEN (NEW.COD_VIDEO IS NULL) 
BEGIN
:new.cod_VIDEO := T_IUD_VIDEO_PROD_COD_VIDEO.nextval;

end;
/






INSERT INTO  T_IUD_CARGOS (ds_cargo) VALUES ('ANALISTA');
INSERT INTO  T_IUD_CARGOS (ds_cargo) VALUES ('SUPORTE');
SELECT * FROM T_IUD_CARGOS;

INSERT INTO  T_IUD_DEPARTAMENTO (ds_dp) VALUES ('TI');
INSERT INTO  T_IUD_DEPARTAMENTO (ds_dp) VALUES ('COMERCIAL');
INSERT INTO  T_IUD_DEPARTAMENTO (ds_dp) VALUES ('FINANCEIRO');
SELECT * FROM T_IUD_DEPARTAMENTO;

INSERT INTO T_IUD_GENERO_CLI (cod_genero) VALUES ('F');
INSERT INTO T_IUD_GENERO_CLI (cod_genero) VALUES ('M');
SELECT * FROM T_IUD_GENERO_CLI;


INSERT INTO T_IUD_TIPO_CLIENTE (ds_tipo) VALUES ('PF');
INSERT INTO  T_IUD_TIPO_CLIENTE (ds_tipo) VALUES ('PJ');
SELECT * FROM  T_IUD_TIPO_CLIENTE ;


INSERT INTO  T_IUD_TIPO_CHAMADO (ds_chamado) VALUES ('SUGESTÃO');
INSERT INTO  T_IUD_TIPO_CHAMADO (ds_chamado) VALUES ('RECLAMACÃO');
SELECT * FROM T_IUD_TIPO_CHAMADO ;

INSERT INTO  T_IUD_STATUS_VIDEO (cod_status_video,ds_status) VALUES ('A','ATIVO');
INSERT INTO  T_IUD_STATUS_VIDEO (cod_status_video,ds_status) VALUES ('I','INATIVO');
SELECT * FROM T_IUD_STATUS_VIDEO;


INSERT INTO  T_IUD_STATUS_CHAM (cod_st_chamado,ds_st_chamado) values('A','ABERTO');
INSERT INTO  T_IUD_STATUS_CHAM (cod_st_chamado,ds_st_chamado) values('E','EM ATENDIMENTO');
INSERT INTO  T_IUD_STATUS_CHAM (cod_st_chamado,ds_st_chamado) values('C','CANCELADO');
INSERT INTO  T_IUD_STATUS_CHAM (cod_st_chamado,ds_st_chamado) values('F','FECHADO COM SUCESSO');
INSERT INTO  T_IUD_STATUS_CHAM (cod_st_chamado,ds_st_chamado) values('X','FECHADO COM INSATISFACAO');
SELECT * FROM T_IUD_STATUS_CHAM;


INSERT INTO T_IUD_STATUS_CAT(cod_status_cat,ds_status) VALUES ('A','ATIVO');
INSERT INTO T_IUD_STATUS_CAT (cod_status_cat,ds_status) VALUES ('I','INATIVO');
SELECT * FROM T_IUD_STATUS_CAT;


INSERT INTO T_IUD_CATEGORIA_PROD (DS_CATEGORIA,DT_INICIO,COD_STATUS_CAT) VALUES('INFORMATICA',CURRENT_TIMESTAMP,'A');
SELECT * FROM T_IUD_CATEGORIA_PROD;

INSERT INTO  T_IUD_STATUS_PROD (cod_status_prod,ds_status) VALUES ('A','ATIVO');
INSERT INTO  T_IUD_STATUS_PROD( cod_status_prod,ds_status) VALUES ('I','INATIVO');
INSERT INTO  T_IUD_STATUS_PROD (cod_status_prod,ds_status) VALUES ('P','PROSPECÇÃO');
SELECT * FROM  T_IUD_STATUS_PROD ;

INSERT INTO  T_IUD_CATEGORIA_VIDEO (nm_cat_video) VALUES ('Instalação do produto');
INSERT INTO  T_IUD_CATEGORIA_VIDEO (nm_cat_video) VALUES ('Uso no cotidiano'); 
INSERT INTO  T_IUD_CATEGORIA_VIDEO (nm_cat_video) VALUES ('Comercial com personalidadeo'); 
SELECT * FROM T_IUD_CATEGORIA_VIDEO;

INSERT INTO T_IUD_CADASTRO(NM_NOME,DDD_TEL,DT_NASC,EMAIL) VALUES ('RICARDO FRASSON','11976692944','02/06/1982','rm94019@fiap.com.br');
INSERT INTO T_IUD_CLIENTE(COD_CADASTRO,DT_ULT_ACESSO,COD_TIPO,COD_GENERO) VALUES (1,CURRENT_TIMESTAMP,1,'M');
SELECT * FROM T_IUD_CADASTRO;

INSERT INTO t_iud_produto (nm_produto,desc_produto,cod_barras,vl_un, cod_categoria,cod_status_prod) VALUES ('MACBOOK PRO','APPLE MACBOOK M1 8GB 128SSD','9287390293020382',10990,1,'A');
SELECT * FROM t_iud_produto ;


INSERT INTO T_IUD_VIDEO_PROD(LINK_VIDEO,COD_PRODUTO,COD_STATUS_VIDEO,COD_CAT_VIDEO) VALUES ('YOUTUBE.COM.BR',1,'A',1);
SELECT * FROM T_IUD_VIDEO_PROD;

INSERT INTO T_IUD_VIEWS_VIDEO(COD_VIDEO,DT_VISITA,COD_CADASTRO) VALUES (1,CURRENT_TIMESTAMP,1);
INSERT INTO T_IUD_VIEWS_VIDEO(COD_VIDEO,DT_VISITA,COD_CADASTRO) VALUES (1,CURRENT_TIMESTAMP,null);
SELECT * FROM T_IUD_VIEWS_VIDEO;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            19
-- CREATE INDEX                             2
-- ALTER TABLE                             39
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           6
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          6
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
